### ISSUE TITLE
I got the following "No such file or directory" error

### ISSUE THREAD

**Issue by messenjah** [citrusbyte/pimotion#1]
OSError: [Errno 2] No such file or directory: 'captures/2015-01-15T19:23:02.144696/'

So i just created a directory "captures" in the same Folder where the main.py exists.

Don't know why but that fixed it, maybe it helps someone.

**Comment by sarahhenkens** [comment]
Thanks for reporting @messenjah. This is indeed a setup bug that happens when running pimotion for the first time.

**Comment by inkel** [comment]
@jellehenkens is there a way to fix that?

**Comment by sarahhenkens** [comment]
Yup, we just check for the existence of that directory and create it on startup or commit the empty directory in the source tree.

**Comment by messenjah** [comment]
Thank you guys for the fast reply!

I am still playing around with your nice python script and it's also
important to have the "montage" tool installed. It is included in the
'imagemagick' package for example and i just installed it. otherwise you
will get a "/bin/sh montage file not found" error.

Now i am at the point that it runs fine until uploading the montage file to
CloudApp. The next step is to learn how M2X works because i am new to this.

I'll keep you up to date.

2015-01-15 20:40 GMT+01:00 Jelle Henkens notifications@github.com:

**Comment by inkel** [comment]
Thank you @messenjah for your feedback! We'll work on those fixes in order to make the installation & bootstrap process smoother. As for M2X, I'd recommend visiting the [Developer Portal](https://m2x.att.com/), the [Get Started](https://m2x.att.com/developer/get-started) tutorial and the [API Documentation](https://m2x.att.com/developer/documentation). We also hang in the `#m2x` channel in `irc.freenode.net` if you have any questions about it.
